# Generated by Django 4.2.6 on 2023-10-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',), 'verbose_name_plural': 'Items'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='isSold',
            new_name='is_sold',
        ),
    ]
